# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paul on GitHub
tagline:          'Fun With Data'
baseurl:          /

author:
  name:           'Paul Hively'
  url:            http://phively.github.io/

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/phively/
