# Dependencies
encoding:           UTF-8
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          pretty

# Setup
title:              Paul on GitHub
tagline:            'Fun With Data'
baseurl:            /

author:
 name:              'Paul Hively'
 url:               //phively.github.io

paginate:           5

# Custom vars
version:            0.4.0

github:
 repo:              //github.com/phively/

footer-links:
 email:             pbhively@gmail.com
 linkedin:          paulhively
 github:            phively